#!/usr/bin/env bash
# Generate transient packaging build metadata for the frozen .app.
#
# Writes src/acqstore_server/_build_info.py (gitignored; removed after pack).
# Do not commit the generated file.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/_config.sh"

if [[ -z "${BUILD_INFO_PATH:-}" ]]; then
  echo "ERROR: BUILD_INFO_PATH is not set in _config.sh" >&2
  exit 2
fi

mkdir -p "$(dirname "$BUILD_INFO_PATH")"

APP_VERSION="$(grep -E '^version[[:space:]]*=' "$REPO_ROOT/pyproject.toml" 2>/dev/null | head -1 | sed -E 's/^version[[:space:]]*=[[:space:]]*["'\'' ]*([^"'\'' ]+)["'\'' ]*.*/\1/')"
APP_VERSION="${APP_VERSION:-0.0.0}"

ACQSTORE_VERSION="$(python - <<'PY'
from importlib import metadata
try:
    print(metadata.version('acqstore'))
except metadata.PackageNotFoundError:
    print('unknown')
PY
)"

GIT_COMMIT="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
GIT_COMMIT_FULL="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"

# US Eastern (Baltimore uses America/New_York). Example:
#   2026-08-05 21:41:00 EDT (Baltimore)
BUILD_TIMESTAMP_EASTERN="$(TZ=America/New_York date '+%Y-%m-%d %H:%M:%S %Z (Baltimore)')"

# Escape single quotes for embedding in a Python string literal.
_py_quote() {
  printf "%s" "${1//\'/\\\'}"
}

PY_APP_VERSION="$(_py_quote "$APP_VERSION")"
PY_ACQSTORE_VERSION="$(_py_quote "$ACQSTORE_VERSION")"
PY_GIT_COMMIT="$(_py_quote "$GIT_COMMIT")"
PY_GIT_COMMIT_FULL="$(_py_quote "$GIT_COMMIT_FULL")"
PY_BUILD_TS="$(_py_quote "$BUILD_TIMESTAMP_EASTERN")"

cat > "$BUILD_INFO_PATH" <<PY
"""Auto-generated build metadata.

Generated by packaging/acqstore_server/build_info.sh. Do not edit or commit.
"""

BUILD_INFO = {
    'version': '${PY_APP_VERSION}',
    'acqstore_version': '${PY_ACQSTORE_VERSION}',
    'git_commit': '${PY_GIT_COMMIT}',
    'git_commit_full': '${PY_GIT_COMMIT_FULL}',
    'build_timestamp_eastern': '${PY_BUILD_TS}',
}
PY

echo "[build-info] Wrote $BUILD_INFO_PATH"
echo "[build-info] version                 : $APP_VERSION"
echo "[build-info] acqstore_version        : $ACQSTORE_VERSION"
echo "[build-info] git_commit              : $GIT_COMMIT"
echo "[build-info] build_timestamp_eastern : $BUILD_TIMESTAMP_EASTERN"

if [[ -n "${BUILD_INFO_JSON_PATH:-}" ]]; then
  mkdir -p "$(dirname "$BUILD_INFO_JSON_PATH")"
  BUILD_INFO_JSON_PATH="$BUILD_INFO_JSON_PATH" \
  BUILD_INFO_VERSION="$APP_VERSION" \
  BUILD_INFO_ACQSTORE_VERSION="$ACQSTORE_VERSION" \
  BUILD_INFO_GIT_COMMIT="$GIT_COMMIT" \
  BUILD_INFO_GIT_COMMIT_FULL="$GIT_COMMIT_FULL" \
  BUILD_INFO_TIMESTAMP_EASTERN="$BUILD_TIMESTAMP_EASTERN" \
  python - <<'PY'
import json
import os
from pathlib import Path

payload = {
    'version': os.environ['BUILD_INFO_VERSION'],
    'acqstore_version': os.environ['BUILD_INFO_ACQSTORE_VERSION'],
    'git_commit': os.environ['BUILD_INFO_GIT_COMMIT'],
    'git_commit_full': os.environ['BUILD_INFO_GIT_COMMIT_FULL'],
    'build_timestamp_eastern': os.environ['BUILD_INFO_TIMESTAMP_EASTERN'],
}
path = Path(os.environ['BUILD_INFO_JSON_PATH'])
path.write_text(json.dumps(payload, indent=2) + '\n')
print(f'[build-info] Wrote {path}')
PY
fi
